CREATE TABLE CLIENTE (
    id NUMBER GENERATED BY DEFAULT AS IDENTITY(START WITH 1 INCREMENT BY 1),
    nombre VARCHAR2(30) NOT NULL,
    rut VARCHAR2(10) NOT NULL UNIQUE,
    direccion VARCHAR2(60),
    PRIMARY KEY (id)
);

CREATE TABLE PRODUCTO (
    id NUMBER GENERATED BY DEFAULT AS IDENTITY(START WITH 1 INCREMENT BY 1),
    nombre VARCHAR2(30) NOT NULL,
    descripcion VARCHAR2(100),
    valor_unitario NUMBER NOT NULL,
    id_categoria NUMBER,
    PRIMARY KEY (id),
    FOREIGN KEY (id_categoria) REFERENCES categoria(id)
);

CREATE TABLE FACTURA (
    numero_factura NUMBER(10) GENERATED BY DEFAULT AS IDENTITY(START WITH 1 INCREMENT BY 1),
    fecha_factura DATE NOT NULL,
    subtotal NUMBER,
    iva NUMBER,
    precio_total NUMBER,
    PRIMARY KEY (numero_factura)
);

CREATE TABLE LISTA_PRODUCTO (
    id NUMBER GENERATED BY DEFAULT AS IDENTITY(START WITH 1 INCREMENT BY 1),
    numero_factura NUMBER(10) NOT NULL,
    id_producto NUMBER NOT NULL,
    valor_unitario NUMBER NOT NULL,
    cantidad NUMBER NOT NULL,
    PRIMARY KEY (id),
    FOREIGN KEY (numero_factura) REFERENCES factura(numero_factura),
    FOREIGN KEY (id_producto) REFERENCES producto(id)
);


CREATE TABLE COMPRA (
    id NUMBER GENERATED BY DEFAULT AS IDENTITY(START WITH 1 INCREMENT BY 1),
    numero_factura NUMBER(10) NOT NULL,
    id_cliente NUMBER NOT NULL,
    FOREIGN KEY (numero_factura) REFERENCES factura(numero_factura),
    FOREIGN KEY (id_cliente) REFERENCES cliente(id),
    PRIMARY KEY (id)
);

CREATE TABLE CATEGORIA (
    id NUMBER GENERATED BY DEFAULT AS IDENTITY(START WITH 1 INCREMENT BY 1),
    nombre VARCHAR2(30) NOT NULL,
    descripcion VARCHAR2(100),
    PRIMARY KEY (id)
);

SELECT * FROM cliente;
SELECT * FROM producto;
SELECT * FROM factura;
SELECT * FROM lista_producto;
SELECT * FROM compra;
SELECT * FROM categoria;

INSERT INTO cliente (nombre, rut, direccion) VALUES ('Alejandra Colicheo','1-9', 'Antonio Varas 5538');
INSERT INTO cliente (nombre, rut, direccion) VALUES ('Pascale Sierralta','1-8', 'Antonio Varas 5538');
INSERT INTO cliente (nombre, rut, direccion) VALUES ('Alicia Troncoso','1-7', 'Las tres marias 242');
INSERT INTO cliente (nombre, rut, direccion) VALUES ('Tomas Arancibia','1-6', 'La Torre 372');
INSERT INTO cliente (nombre, rut, direccion) VALUES ('Roque Sierralta','1-5', 'Recreo 5568');

INSERT INTO categoria (nombre, descripcion) VALUES ('Carnes', 'Carne de vacuno, cerdo o pollo');
INSERT INTO categoria (nombre, descripcion) VALUES ('Licores', 'varios');
INSERT INTO categoria (nombre, descripcion) VALUES ('Verduras/Abarrotes', 'varios');

INSERT INTO producto (nombre, descripcion, valor_unitario, id_categoria) VALUES ('Carne de vacuno','Lomo vetado 1k', 12500, 5);
INSERT INTO producto (nombre, descripcion, valor_unitario, id_categoria) VALUES ('Carne de cerdo','Entraña 1k', 12500, 5);
INSERT INTO producto (nombre, descripcion, valor_unitario, id_categoria) VALUES ('Cerveza Schofferhofer','Lata 500cc', 800, 6);
INSERT INTO producto (nombre, descripcion, valor_unitario, id_categoria) VALUES ('Cerveza Baltica','Pack 12x350cc', 4000, 6);
INSERT INTO producto (nombre, descripcion, valor_unitario, id_categoria) VALUES ('Vino Tinto Gato','Botellon 2L', 3800, 6);
INSERT INTO producto (nombre, descripcion, valor_unitario, id_categoria) VALUES ('Huevo','Bandeja x30', 4500, 7);
INSERT INTO producto (nombre, descripcion, valor_unitario, id_categoria) VALUES ('Pimenton','Verde', 2500, 7);
INSERT INTO producto (nombre, descripcion, valor_unitario, id_categoria) VALUES ('Champiñon','Bandeja 250gr', 1500, 7);

INSERT INTO FACTURA (fecha_factura, subtotal,iva,precio_total) VALUES (TO_DATE('2020/11/8','yyyy/mm/dd'),7800, 1482, 9282);
INSERT INTO FACTURA (fecha_factura, subtotal,iva,precio_total) VALUES (TO_DATE('2020/11/8','yyyy/mm/dd'),8500, 1615, 10115);
INSERT INTO FACTURA (fecha_factura, subtotal,iva,precio_total) VALUES (TO_DATE('2020/11/8','yyyy/mm/dd'),29500, 5605, 35105);
INSERT INTO FACTURA (fecha_factura, subtotal,iva,precio_total) VALUES (TO_DATE('2020/11/8','yyyy/mm/dd'),4000, 760, 4760);
INSERT INTO FACTURA (fecha_factura, subtotal,iva,precio_total) VALUES (TO_DATE('2020/11/8','yyyy/mm/dd'),8600, 1634, 10234);
INSERT INTO FACTURA (fecha_factura, subtotal,iva,precio_total) VALUES (TO_DATE('2020/11/8','yyyy/mm/dd'),800, 152, 952);
INSERT INTO FACTURA (fecha_factura, subtotal,iva,precio_total) VALUES (TO_DATE('2020/11/8','yyyy/mm/dd'),25000, 4750, 29750);
INSERT INTO FACTURA (fecha_factura, subtotal,iva,precio_total) VALUES (TO_DATE('2020/11/8','yyyy/mm/dd'),18800, 3572, 22372);
INSERT INTO FACTURA (fecha_factura, subtotal,iva,precio_total) VALUES (TO_DATE('2020/11/8','yyyy/mm/dd'),10600, 2014, 12614);
INSERT INTO FACTURA (fecha_factura, subtotal,iva,precio_total) VALUES (TO_DATE('2020/11/8','yyyy/mm/dd'),800, 152, 952);

INSERT INTO LISTA_PRODUCTO (numero_factura, id_producto, valor_unitario, cantidad) VALUES (1, 5, 4000, 1);
INSERT INTO LISTA_PRODUCTO (numero_factura, id_producto, valor_unitario, cantidad) VALUES (1, 6, 3800, 1);
INSERT INTO LISTA_PRODUCTO (numero_factura, id_producto, valor_unitario, cantidad) VALUES (2, 7, 4500, 1);
INSERT INTO LISTA_PRODUCTO (numero_factura, id_producto, valor_unitario, cantidad) VALUES (2, 8, 2500, 1);
INSERT INTO LISTA_PRODUCTO (numero_factura, id_producto, valor_unitario, cantidad) VALUES (2, 9, 1500, 1);

INSERT INTO LISTA_PRODUCTO (numero_factura, id_producto, valor_unitario, cantidad) VALUES (3, 2, 12500, 1);
INSERT INTO LISTA_PRODUCTO (numero_factura, id_producto, valor_unitario, cantidad) VALUES (3, 3, 12500, 1);
INSERT INTO LISTA_PRODUCTO (numero_factura, id_producto, valor_unitario, cantidad) VALUES (3, 7, 4500, 1);
INSERT INTO LISTA_PRODUCTO (numero_factura, id_producto, valor_unitario, cantidad) VALUES (4, 8, 2500, 1);
INSERT INTO LISTA_PRODUCTO (numero_factura, id_producto, valor_unitario, cantidad) VALUES (4, 9, 1500, 1);
INSERT INTO LISTA_PRODUCTO (numero_factura, id_producto, valor_unitario, cantidad) VALUES (5, 4, 800, 1);
INSERT INTO LISTA_PRODUCTO (numero_factura, id_producto, valor_unitario, cantidad) VALUES (5, 5, 4000, 1);
INSERT INTO LISTA_PRODUCTO (numero_factura, id_producto, valor_unitario, cantidad) VALUES (5, 6, 3800, 1);

INSERT INTO LISTA_PRODUCTO (numero_factura, id_producto, valor_unitario, cantidad) VALUES (6, 4, 800, 1);

INSERT INTO LISTA_PRODUCTO (numero_factura, id_producto, valor_unitario, cantidad) VALUES (7, 2, 12500, 1);
INSERT INTO LISTA_PRODUCTO (numero_factura, id_producto, valor_unitario, cantidad) VALUES (7, 3, 12500, 1);
INSERT INTO LISTA_PRODUCTO (numero_factura, id_producto, valor_unitario, cantidad) VALUES (8, 3, 12500, 1);
INSERT INTO LISTA_PRODUCTO (numero_factura, id_producto, valor_unitario, cantidad) VALUES (8, 6, 3800, 1);
INSERT INTO LISTA_PRODUCTO (numero_factura, id_producto, valor_unitario, cantidad) VALUES (8, 8, 2500, 1);
INSERT INTO LISTA_PRODUCTO (numero_factura, id_producto, valor_unitario, cantidad) VALUES (9, 9, 1500, 1);
INSERT INTO LISTA_PRODUCTO (numero_factura, id_producto, valor_unitario, cantidad) VALUES (9, 4, 800, 1);
INSERT INTO LISTA_PRODUCTO (numero_factura, id_producto, valor_unitario, cantidad) VALUES (9, 6, 3800, 1);
INSERT INTO LISTA_PRODUCTO (numero_factura, id_producto, valor_unitario, cantidad) VALUES (9, 7, 4500, 1);
INSERT INTO LISTA_PRODUCTO (numero_factura, id_producto, valor_unitario, cantidad) VALUES (10, 4, 800, 1);

INSERT INTO compra (numero_factura, id_cliente) VALUES (1,1);
INSERT INTO compra (numero_factura, id_cliente) VALUES (2,1);
INSERT INTO compra (numero_factura, id_cliente) VALUES (3,2);
INSERT INTO compra (numero_factura, id_cliente) VALUES (4,2);
INSERT INTO compra (numero_factura, id_cliente) VALUES (5,2);
INSERT INTO compra (numero_factura, id_cliente) VALUES (6,3);
INSERT INTO compra (numero_factura, id_cliente) VALUES (7,4);
INSERT INTO compra (numero_factura, id_cliente) VALUES (8,4);
INSERT INTO compra (numero_factura, id_cliente) VALUES (9,4);
INSERT INTO compra (numero_factura, id_cliente) VALUES (10,4);

--EL CLIENTE QUE REALIZO LA COMPRA MAS CARA
SELECT
cl.* 
FROM cliente cl 
INNER JOIN compra c 
ON cl.id = c.id_cliente 
WHERE c.id = (SELECT c.id FROM compra c INNER JOIN factura f ON c.numero_factura = f.numero_factura WHERE f.precio_total = (SELECT MAX(precio_total) FROM factura));

--CLIENTES QUE PAGARON SOBRE 100
SELECT DISTINCT
cl.*
FROM cliente cl 
INNER JOIN compra c 
ON cl.id = c.id_cliente 
WHERE c.id_cliente 
IN (SELECT DISTINCT c.id_cliente FROM compra c INNER JOIN factura f ON c.numero_factura = f.numero_factura WHERE f.precio_total > 100);

--CLIENTES QUE HAN PAGADO EL PRODUCTO 6
SELECT DISTINCT
cl.*
FROM cliente cl 
INNER JOIN compra c 
ON cl.id = c.id_cliente 
WHERE c.id_cliente 
IN (SELECT DISTINCT c.id_cliente FROM compra c INNER JOIN factura f ON c.numero_factura = f.numero_factura WHERE f.numero_factura IN (SELECT f.numero_factura FROM factura f 
                                                                                   INNER JOIN lista_producto l ON l.numero_factura = f.numero_factura WHERE l.id_producto= 6));
